"""Generate the Northwind synthetic corpus: a fictional company with messy files.

Usage: python samples/northwind/generate.py OUTPUT_DIR

OUTPUT_DIR must be new, empty, or a previous Northwind output (it contains the
marker file); anything else is refused so real folders are never overwritten.
All facts are invented. Needs the `ingest` extra (python-docx, openpyxl,
python-pptx, Pillow).
"""

import csv
import random
import shutil
import sys
from pathlib import Path

from docx import Document
from openpyxl import Workbook
from PIL import Image, ImageDraw, ImageFont
from pptx import Presentation

MARKER = ".northwind-corpus"

if len(sys.argv) != 2:
    sys.exit("usage: generate.py OUTPUT_DIR")
ROOT = Path(sys.argv[1]).expanduser().resolve()
if ROOT.exists() and any(ROOT.iterdir()):
    if not (ROOT / MARKER).is_file():
        sys.exit(f"refusing to overwrite {ROOT}: not empty and not a Northwind output")
    shutil.rmtree(ROOT)
ROOT.mkdir(parents=True)
(ROOT / MARKER).write_text("Generated by samples/northwind/generate.py\n")
random.seed(7)


def out(rel: str) -> Path:
    """Path for a corpus file, creating its folders."""
    p = ROOT / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    return p


def md(rel, title, sections):
    """Write a Markdown document."""
    body = f"# {title}\n\n" + "\n\n".join(f"## {h}\n\n{t}" for h, t in sections) + "\n"
    out(rel).write_text(body, encoding="utf-8")


def docx(rel, title, sections, table=None):
    """Write a Word document, optionally with one table."""
    d = Document()
    d.add_heading(title, 0)
    for h, t in sections:
        d.add_heading(h, 1)
        for para in t.split("\n\n"):
            d.add_paragraph(para)
    if table:
        head, rows = table
        tb = d.add_table(rows=1, cols=len(head))
        for i, c in enumerate(head):
            tb.rows[0].cells[i].text = str(c)
        for r in rows:
            cells = tb.add_row().cells
            for i, c in enumerate(r):
                cells[i].text = str(c)
    d.save(out(rel))


def xlsx(rel, sheets):
    """Write a workbook with one sheet per mapping entry."""
    wb = Workbook()
    wb.remove(wb.active)
    for name, rows in sheets.items():
        ws = wb.create_sheet(name)
        for r in rows:
            ws.append(list(r))
    wb.save(out(rel))


def pptx(rel, slides):
    """Write a slide deck of title-and-bullets slides."""
    pr = Presentation()
    for title, bullets in slides:
        s = pr.slides.add_slide(pr.slide_layouts[1])
        s.shapes.title.text = title
        tf = s.placeholders[1].text_frame
        tf.text = bullets[0]
        for b in bullets[1:]:
            tf.add_paragraph().text = b
    pr.save(out(rel))


def pdf(rel, pages):
    """Minimal text PDF; each page is a list of (size, text) lines (ASCII)."""
    objs = [
        "<< /Type /Catalog /Pages 2 0 R >>",
        None,
        "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    kids = []
    for lines in pages:
        y, stream = 740, ""
        for size, text in lines:
            text = text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
            stream += f"BT /F1 {size} Tf 60 {y} Td ({text}) Tj ET\n"
            y -= size + 10
        objs.append(f"<< /Length {len(stream)} >>\nstream\n{stream}endstream")
        cid = len(objs)
        objs.append(
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            f"/Resources << /Font << /F1 3 0 R >> >> /Contents {cid} 0 R >>"
        )
        kids.append(len(objs))
    objs[1] = (
        f"<< /Type /Pages /Kids [{' '.join(f'{k} 0 R' for k in kids)}] /Count {len(kids)} >>"
    )
    data, offsets = b"%PDF-1.4\n", []
    for i, o in enumerate(objs, 1):
        offsets.append(len(data))
        data += f"{i} 0 obj\n{o}\nendobj\n".encode()
    xref = len(data)
    data += f"xref\n0 {len(objs) + 1}\n0000000000 65535 f \n".encode()
    data += b"".join(f"{o:010d} 00000 n \n".encode() for o in offsets)
    data += f"trailer\n<< /Size {len(objs) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode()
    out(rel).write_bytes(data)


def doc_pdf(rel, title, sections):
    """Sections flowed onto pages (about 30 lines per page)."""
    lines = [(18, title)]
    for h, t in sections:
        lines.append((14, h))
        for para in t.split("\n\n"):
            words, cur = para.split(), ""
            for w in words:
                if len(cur) + len(w) > 90:
                    lines.append((10, cur))
                    cur = ""
                cur = f"{cur} {w}".strip()
            lines.append((10, cur))
    pages = [lines[i : i + 30] for i in range(0, len(lines), 30)]
    pdf(rel, pages)


def scanned_pdf(rel, title, lines):
    """Image-only PDF: text rendered to pixels, so extraction needs OCR."""
    img = Image.new("L", (1275, 1650), 255)
    draw = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 34)
        big = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 52)
    except OSError:
        font = big = ImageFont.load_default()
    draw.text((100, 100), title, fill=0, font=big)
    y = 220
    for line in lines:
        draw.text((100, y), line, fill=0, font=font)
        y += 60
    img = img.rotate(0.7, fillcolor=255)  # slight skew like a real scan
    img.save(out(rel), "PDF", resolution=150)


# --------------------------------------------------------------------- HR
docx(
    "HR/Policies/Annual Leave Policy 2026.docx",
    "Annual Leave Policy (2026)",
    [
        (
            "Entitlement",
            "Full-time employees receive 25 days of paid annual leave per calendar year, plus public holidays. Part-time staff receive a pro-rata entitlement.",
        ),
        (
            "Carry-over",
            "Up to 5 unused days may be carried into the next year and must be used by 31 March.",
        ),
        (
            "Requesting leave",
            "Submit requests in the HR portal at least two weeks in advance. Your line manager approves or declines within five working days.",
        ),
    ],
)
docx(
    "HR/Policies/Annual Leave Policy 2024.docx",
    "Annual Leave Policy (2024)",
    [
        (
            "Entitlement",
            "Full-time employees receive 22 days of paid annual leave per year.",
        ),
        ("Carry-over", "Unused leave cannot be carried over."),
    ],
)
md(
    "HR/Policies/parental-leave.md",
    "Parental Leave",
    [
        (
            "Primary carers",
            "Primary carers receive 26 weeks of leave at full pay, followed by up to 26 weeks unpaid.",
        ),
        (
            "Secondary carers",
            "Secondary carers receive 4 weeks at full pay, to be taken within the first year.",
        ),
        (
            "Keeping-in-touch days",
            "Up to 10 paid keeping-in-touch days may be worked during leave by mutual agreement.",
        ),
    ],
)
doc_pdf(
    "HR/Policies/Remote Work Policy.pdf",
    "Remote Work Policy",
    [
        (
            "Eligibility",
            "Employees who have completed probation may work remotely up to 3 days per week with manager approval.",
        ),
        (
            "Equipment",
            "Northwind provides a laptop and one monitor. A home-office allowance of 300 GBP is paid once.",
        ),
        (
            "Working abroad",
            "Working from another country requires written approval from HR and is limited to 20 working days per year.",
        ),
    ],
)
code_sections = [
    (
        f"Section {i}: {t}",
        f"This section explains our expectations on {t.lower()}. " * 12
        + f"Breaches of the {t.lower()} rules are reported to the Ethics Officer.",
    )
    for i, t in enumerate(
        [
            "Integrity",
            "Gifts and Hospitality",
            "Conflicts of Interest",
            "Anti-Bribery",
            "Data Protection",
            "Harassment",
            "Health and Safety",
            "Use of Company Assets",
            "Social Media",
            "Speaking Up",
        ],
        1,
    )
]
code_sections[1] = (
    "Section 2: Gifts and Hospitality",
    "Gifts worth more than 50 GBP must be declared in the gifts register within 7 days. Cash gifts must always be refused. "
    * 3,
)
doc_pdf("HR/Policies/Code of Conduct.pdf", "Northwind Code of Conduct", code_sections)
md(
    "HR/Policies/grievance-procedure.md",
    "Grievance Procedure",
    [
        ("Informal stage", "Raise the issue with your line manager first."),
        (
            "Formal stage",
            "Submit a written grievance to HR. A hearing is held within 10 working days and you may bring a colleague or union representative.",
        ),
        (
            "Appeal",
            "Appeals go to a director not previously involved, within 5 working days of the outcome.",
        ),
    ],
)
xlsx(
    "HR/Onboarding/onboarding-checklist.xlsx",
    {
        "Checklist": [
            ("Day", "Task", "Owner"),
            ("Day 1", "Collect laptop and badge", "IT Service Desk"),
            ("Day 1", "Complete right-to-work check", "HR"),
            ("Week 1", "Complete security awareness training", "Employee"),
            ("Week 2", "Set objectives with manager", "Line manager"),
            ("Month 3", "Probation review", "Line manager"),
        ]
    },
)
with open(out("HR/holidays-2026.csv"), "w", newline="") as f:
    csv.writer(f).writerows(
        [
            ("Date", "Holiday"),
            ("2026-01-01", "New Year's Day"),
            ("2026-04-03", "Good Friday"),
            ("2026-04-06", "Easter Monday"),
            ("2026-05-04", "Early May bank holiday"),
            ("2026-12-25", "Christmas Day"),
            ("2026-12-28", "Boxing Day (substitute)"),
        ]
    )
pptx(
    "HR/Benefits/Benefits Overview 2026.pptx",
    [
        (
            "Benefits at Northwind",
            [
                "Pension: company contributes 6% when you contribute 4%",
                "Private medical insurance for you and dependants",
                "Cycle-to-work scheme",
            ],
        ),
        (
            "Wellbeing",
            [
                "Employee assistance line open 24/7",
                "Annual wellbeing allowance of 250 GBP",
            ],
        ),
    ],
)
docx(
    "HR/Recruitment/Interview Guide.docx",
    "Structured Interview Guide",
    [
        (
            "Panel",
            "Every interview panel has at least two interviewers, one of whom has completed interview training.",
        ),
        (
            "Scoring",
            "Score each competency from 1 to 4. Candidates need an average of 3.0 to be offered a role.",
        ),
    ],
)
xlsx(
    "HR/Recruitment/job-grades.xlsx",
    {
        "Grades": [("Grade", "Title", "Salary min (GBP)", "Salary max (GBP)")]
        + [
            (f"G{g}", t, 22000 + g * 9000, 30000 + g * 11000)
            for g, t in enumerate(
                [
                    "Associate",
                    "Specialist",
                    "Senior Specialist",
                    "Lead",
                    "Manager",
                    "Senior Manager",
                    "Director",
                ],
                1,
            )
        ]
    },
)
out("HR/index.md").write_text(
    "# HR department home\n\nWelcome to HR. Our office hours are 9:00 to 17:00, Monday to Friday.\n"
)
out("HR/notes/empty.txt").write_text("")
for i, (topic, fact) in enumerate(
    [
        (
            "Sickness Absence",
            "Report sickness to your manager by 10:00 on the first day. A fit note is required after 7 calendar days.",
        ),
        (
            "Probation",
            "The probation period is 6 months and may be extended once by up to 3 months.",
        ),
        (
            "Overtime",
            "Overtime is paid at 1.5 times the hourly rate for grades G1 to G3 when approved in advance.",
        ),
        (
            "Flexible Working",
            "Employees may request flexible working from day one; decisions are made within 2 months.",
        ),
        (
            "Jury Service",
            "Employees on jury service receive full pay for up to 10 days.",
        ),
        (
            "Bereavement Leave",
            "Up to 5 days paid bereavement leave is available for a close family member.",
        ),
        (
            "Performance Reviews",
            "Performance reviews take place twice a year, in March and September.",
        ),
        (
            "Relocation",
            "The relocation allowance is up to 8,000 GBP for moves of more than 50 miles.",
        ),
    ]
):
    md(
        f"HR/Policies/other/{topic.lower().replace(' ', '-')}.md",
        f"{topic} Policy",
        [("Summary", fact), ("Contact", "Questions go to hr@northwind.example.")],
    )

# ---------------------------------------------------------------- Finance
docx(
    "Finance/Expenses/Expense Policy.docx",
    "Expense Policy",
    [
        (
            "Claims",
            "Submit expense claims within 60 days of the expense, with itemised receipts.",
        ),
        (
            "Meals",
            "Meals while travelling are reimbursed up to 40 GBP per day in the UK and 60 GBP per day abroad.",
        ),
        (
            "Mileage",
            "Business mileage in a private car is paid at 45 pence per mile for the first 10,000 miles.",
        ),
    ],
)
travel = [
    (
        "Booking",
        "Book travel through the Northwind travel desk. Rail is preferred for journeys under 4 hours.",
    ),
    (
        "Flights",
        "Economy class for flights under 7 hours; premium economy above 7 hours. Business class requires CFO approval.",
    ),
    (
        "Hotels",
        "The hotel limit is 150 GBP per night in the UK and 220 GBP per night in London.",
    ),
]
doc_pdf("Finance/Travel/Travel Policy.pdf", "Travel Policy", travel)
doc_pdf(
    "Finance/Travel/Travel Policy FINAL.pdf", "Travel Policy", travel
)  # duplicate content
docx(
    "Finance/Travel/Travel Policy v2 DRAFT.docx",
    "Travel Policy (v2 draft - not approved)",
    [
        (
            "Hotels",
            "Proposed: the hotel limit rises to 180 GBP per night in the UK and 260 GBP in London.",
        ),
    ],
)
xlsx(
    "Finance/Procurement/approval-matrix.xlsx",
    {
        "Purchase approvals": [
            ("Amount (GBP)", "Approver"),
            ("Up to 1,000", "Line manager"),
            ("1,001 to 10,000", "Department head"),
            ("10,001 to 100,000", "Finance Director"),
            ("Over 100,000", "CFO and CEO"),
        ],
        "Quotes required": [
            ("Amount (GBP)", "Quotes"),
            ("Up to 5,000", "1"),
            ("5,001 to 50,000", "3"),
            ("Over 50,000", "Formal tender"),
        ],
    },
)
rows: list[tuple] = [("Cost centre", "Department", "Account", "Q1", "Q2", "Q3", "Q4")]
for cc in range(100, 130):
    for acct in [
        "Salaries",
        "Travel",
        "Software",
        "Training",
        "Facilities",
        "Consulting",
        "Marketing",
        "Equipment",
        "Recruitment",
        "Other",
    ]:
        rows.append(
            (
                f"CC-{cc}",
                random.choice(["HR", "Finance", "IT", "Operations", "Sales"]),
                acct,
                *(random.randrange(1000, 90000, 500) for _ in range(4)),
            )
        )
xlsx("Finance/Budgets/budget-fy2026.xlsx", {"Budget": rows})
with open(out("Finance/Procurement/approved-vendors.csv"), "w", newline="") as f:
    csv.writer(f).writerows(
        [("Vendor", "Category", "Contract end")]
        + [
            (
                f"Vendor {chr(65 + i)}{i}",
                random.choice(
                    ["Logistics", "IT hardware", "Cleaning", "Consulting", "Packaging"]
                ),
                f"2027-{(i % 12) + 1:02d}-28",
            )
            for i in range(40)
        ]
    )
md(
    "Finance/Close/month-end-close.md",
    "Month-End Close",
    [
        (
            "Timetable",
            "Accruals are due by working day 2. Management accounts are issued on working day 5.",
        ),
        ("Owners", "The Financial Controller signs off the close checklist."),
    ],
)
pptx(
    "Finance/Invoices/Invoice Processing SOP.pptx",
    [
        (
            "Invoice processing",
            [
                "All invoices go to invoices@northwind.example",
                "Invoices must quote a valid purchase order number",
            ],
        ),
        (
            "Payment terms",
            [
                "Standard payment terms are 30 days from invoice date",
                "Small suppliers are paid within 14 days",
            ],
        ),
    ],
)
scanned_pdf(
    "Finance/Scans/Petty Cash Procedure (scan).pdf",
    "Petty Cash Procedure",
    [
        "1. Each site holds a petty cash float of 200 GBP.",
        "2. Single purchases above 50 GBP cannot use petty cash.",
        "3. The float is reconciled every Friday by the site administrator.",
        "4. Missing receipts must be reported to the Financial Controller.",
    ],
)
out("Finance/Budgets/broken-report.xlsx").write_bytes(
    b"PK\x03\x04 this is not really a spreadsheet \x00\x01\x02"
)
xlsx(
    "Finance/cost-centres.xlsx",
    {
        "Cost centres": [("Code", "Name", "Owner")]
        + [
            (f"CC-{c}", n, o)
            for c, n, o in [
                (100, "Finance", "Amara Okoye"),
                (110, "HR", "Daniel Price"),
                (120, "IT", "Mei Chen"),
                (125, "Operations", "Luis Romero"),
            ]
        ]
    },
)

# --------------------------------------------------------------------- IT
md(
    "IT/Security/password-policy.md",
    "Password Policy",
    [
        (
            "Length",
            "Passwords must be at least 14 characters. Passphrases are encouraged.",
        ),
        (
            "Rotation",
            "Passwords are not rotated on a schedule; change them only if compromise is suspected.",
        ),
        (
            "MFA",
            "Multi-factor authentication is mandatory for email, VPN and all admin accounts.",
        ),
    ],
)
out("IT/Guides/vpn-setup.html").write_text(
    """<html><head><title>VPN setup</title></head><body>
<h1>Connecting to the Northwind VPN</h1>
<h2>Install</h2><p>Install the GlobalConnect client from the Software Centre.</p>
<h2>Connect</h2><p>Use the gateway <b>vpn.northwind.example</b> and sign in with your email and MFA.</p>
<h2>Troubleshooting</h2><p>If the connection drops every hour, update the client to version 6.2 or later.</p>
</body></html>""",
    encoding="utf-8",
)
docx(
    "IT/Hardware/Laptop Standard.docx",
    "Standard Laptop Build",
    [
        (
            "Models",
            "Standard staff receive a 14-inch laptop with 16 GB RAM. Engineers receive 32 GB RAM.",
        ),
        (
            "Replacement",
            "Laptops are replaced every 4 years, or earlier if repair costs exceed 40% of replacement cost.",
        ),
    ],
)
doc_pdf(
    "IT/Security/Incident Response Plan.pdf",
    "Security Incident Response Plan",
    [
        (
            "Reporting",
            "Report suspected security incidents to security@northwind.example or call extension 4444, 24 hours a day.",
        ),
        (
            "Severity",
            "Severity 1 incidents require the incident commander to brief the CIO within 1 hour.",
        ),
        (
            "Data breaches",
            "Personal data breaches are assessed by the Data Protection Officer and, where required, reported to the regulator within 72 hours.",
        ),
    ],
)
xlsx(
    "IT/Operations/backup-schedule.xlsx",
    {
        "Backups": [
            ("System", "Frequency", "Retention"),
            ("File servers", "Nightly", "90 days"),
            ("ERP database", "Every 4 hours", "35 days"),
            ("Email", "Continuous", "1 year"),
        ]
    },
)
with open(out("IT/software-catalog.csv"), "w", newline="") as f:
    csv.writer(f).writerows(
        [("Software", "Licence", "Self-service")]
        + [
            (n, lic, s)
            for n, lic, s in [
                ("Office Suite", "Enterprise", "Yes"),
                ("Diagram Pro", "Per user", "No"),
                ("Code Editor", "Free", "Yes"),
                ("CAD Studio", "Per seat", "No"),
            ]
        ]
    )
md(
    "IT/Security/Standards/Crypto/tls-standard.md",
    "TLS Standard",
    [
        (
            "Versions",
            "Only TLS 1.2 and 1.3 are permitted. TLS 1.0 and 1.1 are disabled on all services.",
        ),
        (
            "Certificates",
            "Public certificates are renewed automatically 30 days before expiry.",
        ),
    ],
)
docx(
    "IT/Access/Access Request SOP.docx",
    "Access Request Procedure",
    [
        (
            "Requesting access",
            "Raise an access request in the service portal. Access to finance systems needs approval from the system owner.",
        ),
        (
            "Leavers",
            "Accounts of leavers are disabled on their last working day by 18:00.",
        ),
    ],
)
md(
    "IT/Datenschutz/Richtlinie Datenschutz.md",
    "Datenschutzrichtlinie (Deutschland)",
    [
        (
            "Geltungsbereich",
            "Diese Richtlinie gilt für alle Mitarbeitenden am Standort München.",
        ),
        ("Aufbewahrung", "Bewerbungsunterlagen werden nach sechs Monaten gelöscht."),
    ],
)
out("IT/Diagrams/network.vsdx").write_bytes(b"not a supported format")
out("IT/Hardware/.~lock.Laptop Standard.docx#").write_text("lock file")
for sysname, fact in [
    (
        "ERP",
        "Restart the ERP application tier with the 'erp-restart' job; never restart the database first.",
    ),
    ("Email", "If mail queues exceed 500 messages, fail over to the secondary relay."),
    ("Printers", "Print queues are cleared automatically at 02:00."),
    ("Wi-Fi", "Guest Wi-Fi passwords rotate every Monday at 06:00."),
    (
        "Warehouse Scanners",
        "Scanners re-sync with the WMS every 15 minutes; hold the power button 10 seconds to reset.",
    ),
    (
        "Payroll Interface",
        "The payroll file is sent to the bureau on the 20th of each month.",
    ),
]:
    md(
        f"IT/Runbooks/{sysname.lower().replace(' ', '-')}-runbook.md",
        f"{sysname} Runbook",
        [
            ("Procedure", fact),
            ("Escalation", "Escalate to the on-call engineer via the service desk."),
        ],
    )

# -------------------------------------------------------------- Operations
doc_pdf(
    "Operations/Safety/Warehouse Safety Rules.pdf",
    "Warehouse Safety Rules",
    [
        ("PPE", "Hi-vis vests and safety boots are mandatory in all warehouse zones."),
        (
            "Forklifts",
            "Only licensed operators may drive forklifts. Licences are renewed every 3 years.",
        ),
        ("Speed", "The speed limit for vehicles inside the warehouse is 5 mph."),
    ],
)
xlsx(
    "Operations/Products/sku-catalogue.xlsx",
    {
        "SKUs": [("SKU", "Product", "Warranty (months)", "Lead time (days)")]
        + [
            (
                f"NW-{1000 + i}",
                f"{random.choice(['Bearing', 'Valve', 'Gasket', 'Pump', 'Sensor', 'Coupling'])} type {i}",
                random.choice([12, 24, 36]),
                random.choice([5, 10, 15, 30]),
            )
            for i in range(80)
        ]
    },
)
docx(
    "Operations/Logistics/Shipping SLA.docx",
    "Shipping Service Levels",
    [
        ("Standard", "Orders received by 14:00 ship the same working day."),
        ("Express", "Express orders are delivered next working day within the UK."),
    ],
    table=(
        ["Region", "Standard transit (days)"],
        [["UK", 2], ["EU", 4], ["Rest of world", 7]],
    ),
)
md(
    "Operations/Returns/returns-policy.md",
    "Returns Policy",
    [
        ("Window", "Customers may return unused products within 30 days of delivery."),
        (
            "Faulty goods",
            "Faulty goods are replaced or refunded under warranty after inspection.",
        ),
    ],
)
out("Operations/Returns/returns-policy.txt").write_text(
    "Returns policy (plain text copy for the call centre)\nCustomers may return unused products within 30 days. A restocking fee of 10% applies to special orders.\n"
)
pptx(
    "Operations/Training/Forklift Refresher.pptx",
    [
        (
            "Forklift refresher",
            ["Pre-use checks every shift", "Report defects before operating"],
        ),
        (
            "Loads",
            [
                "Never exceed the rated capacity on the data plate",
                "Travel with forks 15 cm above the floor",
            ],
        ),
    ],
)
docx(
    "Operations/Quality/Supplier Quality Manual.docx",
    "Supplier Quality Manual",
    [
        (
            "Audits",
            "New suppliers are audited before first order and every 2 years after that.",
        ),
        (
            "Non-conformance",
            "Suppliers must send a corrective action plan within 10 working days of a non-conformance report.",
        ),
    ],
)
for site, city, mgr, docks in [
    ("Leeds DC", "Leeds", "Priya Nair", 12),
    ("Bristol DC", "Bristol", "Tom Harris", 8),
    ("Rotterdam Hub", "Rotterdam", "Sanne de Vries", 20),
    ("Glasgow Depot", "Glasgow", "Callum Reid", 4),
    ("Munich Office", "Munich", "Lena Weber", 0),
    ("Coventry Plant", "Coventry", "Jas Singh", 6),
]:
    md(
        f"Operations/Sites/{site.lower().replace(' ', '-')}.md",
        site,
        [
            ("Location", f"{site} is in {city}. Site manager: {mgr}."),
            (
                "Facilities",
                f"The site has {docks} loading docks."
                if docks
                else "Office only; no loading docks.",
            ),
        ],
    )
out("archive/2019-backup.zip").write_bytes(b"PK\x05\x06" + b"\x00" * 18)

print(
    sum(1 for p in ROOT.rglob("*") if p.is_file() and p.name != MARKER),
    "files written to",
    ROOT,
)
